
now=$(date +%s)

### Download hosts
wget https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -O hosts.10-stevenblack
wget https://adaway.org/hosts.txt -O hosts.20-adaway
wget https://someonewhocares.org/hosts/zero/hosts -O hosts.30-danpollock
wget https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt -O hosts.40-goodbyeads
wget 'https://pgl.yoyo.org/adservers/serverlist.php?showintro=1&mimetype=plaintext' -O hosts.50-peterlowe
wget https://hosts.oisd.nl/basic/ -O hosts.60-oisd
echo "#### uAdBlockNG autogenerated hosts ####" > hosts
echo "#### Generated on $(date -d @$now) ####" >> hosts
cat hosts.* >> hosts
echo $now > updated

wget https://raw.githubusercontent.com/marktron/fakenews/master/fakenews -O hosts-fakenews.10-markron
echo "#### uAdBlockNG autogenerated fakenews hosts ####" > hosts-fakenews
echo "#### Generated on $(date -d @$now) ####" >> hosts-fakenews
cat hosts-fakenews.* >> hosts-fakenews
echo $now > updated-fakenews

wget https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts -O hosts-gambling.10-sinfonietta
echo "#### uAdBlockNG autogenerated gambling hosts ####" > hosts-gambling
echo "#### Generated on $(date -d @$now) ####" >> hosts-gambling
cat hosts-gambling.* >> hosts-gambling
echo $now > updated-gambling

wget https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts -O hosts-porn.10-clefspeare13
wget https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts -O hosts-porn.15-sinfonietta
wget https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts -O hosts-porn.20-sinfonietta
echo "#### uAdBlockNG autogenerated porn hosts ####" > hosts-porn
echo "#### Generated on $(date -d @$now) ####" >> hosts-porn
cat hosts-porn.* >> hosts-porn
echo $now > updated-porn

wget https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts -O hosts-social.10-sinfonietta
echo "#### uAdBlockNG autogenerated social hosts ####" > hosts-social
echo "#### Generated on $(date -d @$now) ####" >> hosts-social
cat hosts-social.* >> hosts-social
echo $now > updated-social
